---

- name: netdata installation
  hosts: default

  gather_facts: yes

  become: yes

  tasks:
    - name: get the file for installation
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /root/
        mode: 'u+x,g+x'

    - name: install the file
      shell: bash /root/kickstart.sh all --non-interactive
