---

- name: Netdata installation, does not run
  hosts: default

  gather_facts: yes

  become: yes

  tasks:
    - name: Get the file for installation
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /root/
        mode: 'u+x,g+x'

  # need to double check this bit
    - name: Install the file
      shell: bash /root/kickstart.sh all --non-interactive
